### ISSUE TITLE
I cannot import and export with errors.

### ISSUE THREAD

**Issue by zanze-zz** [ilmheg/MultiAssist#3]
How can I resolve this?
![err](https://user-images.githubusercontent.com/104469242/166391066-5a31472f-69c8-4dc0-b907-cb670b433622.jpg)

**Comment by ilmheg** [comment]
Extremely embarrassing mistake on my behalf, use the _CONSOLE build for now. Thanks for letting me know. I'll restore the non-console version in the next release.

[MultiAssist_v0.2.3_CONSOLE.zip](https://github.com/ilmheg/MultiAssist/files/8617352/MultiAssist_v0.2.3_CONSOLE.zip)

**Comment by zanze-zz** [comment]
It's done! Thank you !
